[package]
name = "pixel-physician-tilr"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
image = { workspace = true }
rayon = { workspace = true }
